### ISSUE TITLE
Ubuntu VM has issues staying connected, even though CONNACK is received

### ISSUE THREAD

**Issue by jspaith** [Azure-Samples/iot-middleware-freertos-samples#43]
I can successfully build / setup Linux following instructions.  I’m on an Ubuntu 20.04 honest VM, going straight to IoT Hub, no DPS, with symmetric key.  All just golden path from instructions.

I can setup my device to successfully connect, including seeing a CONNACK that seems OK.  So far so good.  And I put in a dummy device and symmetric and saw that being correctly rejected, so I think to CONNACK I’m fine.

However the next thing I know, I end up getting an error -128 popping to TLS_Socket_Recv(), and this isn’t an mbed error so it can’t print friendly stuff on it.  (I hand-added error code.)  I debugged some and the error turns out to be pdFREERTOS_ERRNO_ENOTCONN, which is FreeRTOS land.  It seems that after I CONNECt the network gets off right away.  I get this is very unlikely a middleware issue and either freertos|vm_net|pilot error on my part, but would still be helpful to understand.
 

Logs below, see "// Jspaith: " for a few places I have extra commentary.

```log
john@john-ubuntu4:~/iot/iot-middleware-freertos-samples$ sudo ./build_linux/demos/projects/PC/linux/iot-middleware-sample.elf


The following network interfaces are available:

Interface 1 - eth0
              (No description)

Interface 2 - veth0
              (No description)

Interface 3 - veth1
              (No description)

Interface 4 - lo
              (No description)

Interface 5 - any
              (Pseudo-device that captures on all interfaces)

Interface 6 - bluetooth-monitor
              (Bluetooth Linux Monitor)

Interface 7 - nflog
              (Linux netfilter log (NFLOG) interface)

Interface 8 - nfqueue
              (Linux netfilter queue (NFQUEUE) interface)


The interface that will be opened is set by "configNETWORK_INTERFACE_TO_USE", which
should be defined in FreeRTOSConfig.h
Attempting to open interface number 3.
[INFO] [AzureIoTDemo] [vApplicationIPNetworkEventHook:189] ---------STARTING DEMO---------

[INFO] [AzureIoTDemo] [vApplicationIPNetworkEventHook:198]

IP Address: 192.168.1.100

[INFO] [AzureIoTDemo] [vApplicationIPNetworkEventHook:201] Subnet Mask: 255.255.255.0

[INFO] [AzureIoTDemo] [vApplicationIPNetworkEventHook:204] Gateway Address: 192.168.1.1

[INFO] [AzureIoTDemo] [vApplicationIPNetworkEventHook:207] DNS Server Address: 1.1.1.1



[INFO] [AzureIoTDemo] [prvConnectToServerWithBackoffRetries:579] Creating a TLS connection to [redacted].azure-devices.net:8883.

[INFO] [AzureIoTDemo] [prvAzureDemoTask:383] Creating an MQTT connection to [redacted].azure-devices.net.

[INFO] [MQTT] [receivePacket:885] Packet received. ReceivedBytes=2.
[INFO] [MQTT] [deserializeConnack:958] CONNACK session present bit set.
[INFO] [MQTT] [logConnackResponse:912] Connection accepted.
[INFO] [MQTT] [receiveConnack:1563] Received MQTT CONNACK successfully from broker.
[INFO] [MQTT] [MQTT_Connect:1829] MQTT connection established with the broker. // JSpaith: Note we connect OK…
error-not-connected // Jspaith: This is an extra message jspaith put into FReeRTOS layer to make sure this was indeed correct error when run outside of debugger.
[ERROR] [TlsTransport] [TLS_Socket_Recv:869] Failed to read data: mbedTLSError= -128, <No-High-Level-Code> : <No-Low-Level-Code>.
[ERROR] [MQTT] [MQTT_GetIncomingPacketTypeAndLength:2395] A single byte was not read from the transport: transportStatus=-128, status=0.
[ERROR] [MQTT] [receiveSingleIteration:1319] Receiving incoming packet length failed. Status=MQTTRecvFailed
[ERROR] [MQTT] [MQTT_ProcessLoop:2191] Exiting process loop due to failure: ErrorStatus=MQTTRecvFailed
[ERROR] [TlsTransport] [TLS_Socket_Send:913] Failed to send data:  mbedTLSError= <No-High-Level-Code> : <No-Low-Level-Code>.
[ERROR] [MQTT] [sendPacket:625] Transport send failed. Error code=-128.
[ERROR] [MQTT] [MQTT_Subscribe:1892] Transport send failed for SUBSCRIBE packet.
[ERROR] [TlsTransport] [TLS_Socket_Send:913] Failed to send data:  mbedTLSError= <No-High-Level-Code> : <No-Low-Level-Code>.
[ERROR] [MQTT] [sendPacket:625] Transport send failed. Error code=-128.
[ERROR] [MQTT] [MQTT_Subscribe:1892] Transport send failed for SUBSCRIBE packet.
[ERROR] [TlsTransport] [TLS_Socket_Send:913] Failed to send data:  mbedTLSError= <No-High-Level-Code> : <No-Low-Level-Code>.
[ERROR] [MQTT] [sendPacket:625] Transport send failed. Error code=-128.
[ERROR] [MQTT] [sendPublish:1414] Transport send failed for PUBLISH header.
[ERROR] [MQTT] [MQTT_Publish:1972] MQTT PUBLISH failed with status MQTTSendFailed.
[INFO] [AzureIoTDemo] [prvAzureDemoTask:424] Attempt to receive publish message from IoT Hub.

error-not-connected
[ERROR] [TlsTransport] [TLS_Socket_Recv:869] Failed to read data: mbedTLSError= -128, <No-High-Level-Code> : <No-Low-Level-Code>.
[ERROR] [MQTT] [MQTT_GetIncomingPacketTypeAndLength:2395] A single byte was not read from the transport: transportStatus=-128, status=0.
[ERROR] [MQTT] [receiveSingleIteration:1319] Receiving incoming packet length failed. Status=MQTTRecvFailed
[ERROR] [MQTT] [MQTT_ProcessLoop:2191] Exiting process loop due to failure: ErrorStatus=MQTTRecvFailed
[INFO] [AzureIoTDemo] [prvAzureDemoTask:441] Keeping Connection Idle...
```

Call stack from where the FreeRTOS error is hit when running gdb.  In general I worry about timing things esp. becaues this was under debugger, but because this reproed at full speed too and same error pretty sure this is right.

#define pdFREERTOS_ERRNO_ENOTCONN   128 /* Socket is not connected */

```log
#0  FreeRTOS_recv (xSocket=0x7fffec0018b0, pvBuffer=0x7fffec002af8, uxBufferLength=5, xFlags=0) at _deps/freertos-src/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/FreeRTOS_Sockets.c:3076
#1  0x00005555555a98c1 in Sockets_Recv (xSocket=0x7fffec0018b0, pucReceiveBuffer=0x7fffec002af8 "\027\003\003", xReceiveBufferLength=5)
    at ../demos/common/transport/sockets_wrapper_freertos_tcpip.c:157
#2  0x00005555555a95fc in mbedtls_platform_recv (ctx=0x7fffec0018b0, buf=0x7fffec002af8 "\027\003\003", len=5) at ../demos/common/utilities/mbedtls_freertos_port.c:132
#3  0x0000555555588758 in mbedtls_ssl_fetch_input (ssl=0x7fffec000c20, nb_want=5) at _deps/freertos-src/FreeRTOS-Plus/ThirdParty/mbedtls/library/ssl_msg.c:2175
#4  0x00005555555895ae in ssl_get_next_record (ssl=0x7fffec000c20) at _deps/freertos-src/FreeRTOS-Plus/ThirdParty/mbedtls/library/ssl_msg.c:4678
#5  0x00005555555893bc in mbedtls_ssl_read_record (ssl=0x7fffec000c20, update_hs_digest=1) at _deps/freertos-src/FreeRTOS-Plus/ThirdParty/mbedtls/library/ssl_msg.c:4040
#6  0x0000555555589e67 in mbedtls_ssl_read (ssl=0x7fffec000c20, buf=0x7ffff4bc9c50 "p\234\274\364\377\177", len=1)
    at _deps/freertos-src/FreeRTOS-Plus/ThirdParty/mbedtls/library/ssl_msg.c:5505
#7  0x00005555555a91bf in TLS_Socket_Recv (pxNetworkContext=0x7ffff4bc9dc8, pvBuffer=0x7ffff4bc9c50, xBytesToRecv=1)
    at ../demos/common/transport/transport_tls_socket_using_mbedtls.c:850
#8  0x00005555555bcbbf in MQTT_GetIncomingPacketTypeAndLength (readFunc=0x5555555a9172 <TLS_Socket_Recv>, pNetworkContext=0x7ffff4bc9dc8, pIncomingPacket=0x7ffff4bc9c50)
    at ../libs/azure-iot-middleware-freertos/libraries/coreMQTT/source/core_mqtt_serializer.c:2359
#9  0x00005555555b727d in receiveSingleIteration (pContext=0x5555555de6a0 <xAzureIoTHubClient>, remainingTimeMs=10, manageKeepAlive=true)
    at ../libs/azure-iot-middleware-freertos/libraries/coreMQTT/source/core_mqtt.c:1297
#10 0x00005555555b8cb6 in MQTT_ProcessLoop (pContext=0x5555555de6a0 <xAzureIoTHubClient>, timeoutMs=10)
    at ../libs/azure-iot-middleware-freertos/libraries/coreMQTT/source/core_mqtt.c:2185
#11 0x00005555555ac72a in AzureIoTMQTT_ProcessLoop (xContext=0x5555555de6a0 <xAzureIoTHubClient>, ulMilliseconds=10)
    at ../libs/azure-iot-middleware-freertos/ports/coreMQTT/azure_iot_core_mqtt.c:182
#12 0x00005555555aa2ef in prvWaitForSubAck (pxAzureIoTHubClient=0x5555555de6a0 <xAzureIoTHubClient>, pxContext=0x5555555de898 <xAzureIoTHubClient+504>, ulTimeoutMilliseconds=9990)
    at ../libs/azure-iot-middleware-freertos/source/azure_iot_hub_client.c:477
#13 0x00005555555aaf5d in AzureIoTHubClient_SubscribeCloudToDeviceMessage (pxAzureIoTHubClient=0x5555555de6a0 <xAzureIoTHubClient>,
    xCallback=0x5555555a7177 <prvHandleCloudMessage>, prvCallbackContext=0x5555555de6a0 <xAzureIoTHubClient>, ulTimeoutMilliseconds=10000)
    at ../libs/azure-iot-middleware-freertos/source/azure_iot_hub_client.c:952
#14 0x00005555555a7784 in prvAzureDemoTask (pvParameters=0x0) at ../demos/sample_azure_iot/sample_azure_iot.c:390
#15 0x000055555555ebef in prvWaitForStart (pvParams=0x7ffff0018968) at _deps/freertos-src/FreeRTOS/Source/portable/ThirdParty/GCC/Posix/port.c:435
#16 0x00007ffff7f9a609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#17 0x00007ffff7e76293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
`

**Comment by jspaith** [comment]
I just attempted to repro with the latest middleware / SDK, and no repo.  My hub was in state of needing to be renewed so there's a non-0 chance that Hub itself was closing this down; unfortunately I didn't think of this until much later to actually testing with same device of another SDK.

Anyway no repo==closing.
